version: "3.8"

services:
  mysql:
    image: jbaricot/mysql:despliegue_dockercompose
    container_name: "mysql_container_3"
    environment:
      MYSQL_ROOT_PASSWORD: asd123
      MYSQL_DATABASE : my_db
      MYSQL_USER: jbaricot
      MYSQL_PASSWORD: asdf1234
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      mynetwork:
        ipv4_address: 192.168.20.100

  phpmyadmin: 
    image: jbaricot/phpmyadmin:despliegue_dockercompose
    container_name: "phpmyadmin_container_3"
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql_container_3
      MYSQL_ROOT_PASSWORD: asd123
      PMA_USER: jbaricot
      PMA_PASSWORD: asdf1234
      PMA_CONTROLUSER: jbaricot
      PMA_CONTROLPASS: asdf1234
    depends_on:
      - mysql
    volumes:
      - phpmyadmin-volume:/etc/phpmyadmin
    networks:
      mynetwork:
        ipv4_address: 192.168.20.101
      
volumes:
  mysql-volume:
    external: true
  phpmyadmin-volume:
    external: true
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24