apiVersion: v1
kind: Service

metadata:
  name: phpmyadmin-service  # Nombre del servicio
  labels:
    app: web-phpmyadmin     # Etiqueta para el servicio
    version: v1             # Versión del servicio

spec:
  type: NodePort            # Tipo de servicio, expone el servicio en un puerto de cada nodo
  selector:
    microservice: phpmyadmin  # Selecciona los pods con la etiqueta 'microservice: phpmyadmin'
  ports:
    - protocol: TCP
      port: 80              # Puerto en el que el servicio estará disponible dentro del clúster
      targetPort: 80        # Puerto en el que el contenedor escucha

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-phpmyadmin       # Nombre del deployment
  labels:
    app: phpmyadmin          # Etiqueta para el deployment

spec:
  selector:
    matchLabels:
      proyecto: web-phpmyadmin  # Selecciona los pods con la etiqueta 'proyecto: web-phpmyadmin'
  replicas: 2                  # Número de replicas del pod

  template:
    metadata:
      name: pod-phpmyadmin     # Nombre del pod
      labels:
        proyecto: web-phpmyadmin  # Etiqueta para los pods

    spec:
      containers:
        - name: phpmyadmin     # Nombre del contenedor
          image: jbaricot/phpmyadmin:v1  # Imagen del contenedor a usar
          ports:
            - containerPort: 80  # Puerto en el que el contenedor escucha
          env:
            - name: PMA_HOST
              value: mysql_container  # Variable de entorno PMA_HOST
            - name: MYSQL_ROOT_PASSWORD
              value: jbaricot         # Variable de entorno MYSQL_ROOT_PASSWORD
            - name: PMA_USER
              value: jbaricot         # Variable de entorno PMA_USER
            - name: PMA_PASSWORD
              value: asdf1234         # Variable de entorno PMA_PASSWORD
          volumeMounts:
            - name: persistent-storage-phpmyadmin
              mountPath: /etc/phpmyadmin  # Monta el volumen persistente en /etc/phpmyadmin
      volumes:
        - name: persistent-storage-phpmyadmin
          persistentVolumeClaim:
            claimName: pvc-phpmyadmin  # Refiere a un PersistentVolumeClaim llamado 'pvc-phpmyadmin'
