apiVersion: v1
kind: Service

metadata:
  name: mysql-service  # Nombre del servicio
  labels:
    app: web-phpmyadmin     # Etiqueta para el servicio
    version: v1             # Versión del servicio

spec:
  type: ClusterIP           # Tipo de servicio, expone el servicio internamente dentro del clúster
  selector:
    microservice: mysql     # Selecciona los pods con la etiqueta 'microservice: mysql'
  ports:
    - protocol: TCP
      port: 3306            # Puerto en el que el servicio estará disponible dentro del clúster
      targetPort: 3306      # Puerto en el que el contenedor escucha

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-phpmyadmin       # Nombre del deployment
  labels:
    app: phpmyadmin            # Etiqueta para el deployment

spec:
  selector:
    matchLabels:
      proyecto: mysql-phpmyadmin  # Selecciona los pods con la etiqueta 'proyecto: mysql-phpmyadmin'
  replicas: 2                    # Número de replicas del pod

  template:
    metadata:
      name: pod-mysql           # Nombre del pod
      labels:
        proyecto: mysql-phpmyadmin  # Etiqueta para los pods

    spec:
      containers:
        - name: mysql            # Nombre del contenedor
          image: jbaricot/mysql:v1  # Imagen del contenedor a usar
          ports:
            - containerPort: 3306  # Puerto en el que el contenedor escucha
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: asd123          # Variable de entorno MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: my_db           # Variable de entorno MYSQL_DATABASE
            - name: MYSQL_USER
              value: jbaricot        # Variable de entorno MYSQL_USER
            - name: MYSQL_PASSWORD
              value: asdf1234        # Variable de entorno MYSQL_PASSWORD
          volumeMounts:
            - name: persistent-storage-mysql
              mountPath: /var/lib/mysql  # Monta el volumen persistente en /var/lib/mysql
      volumes:
        - name: persistent-storage-mysql
          persistentVolumeClaim:
            claimName: pvc-mysql  # Refiere a un PersistentVolumeClaim llamado 'pvc-mysql'
