apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql  # Nombre del PersistentVolumeClaim

spec:
  accessModes:
    - ReadWriteMany  # Modo de acceso, permite que múltiples nodos puedan leer y escribir en el volumen
  resources:
    requests:
      storage: 5Gi  # Solicitud de almacenamiento de 5 GiB para este PersistentVolumeClaim
